import Beranda from './Beranda/index'
import ListDataPenduduk from './DataPenduduk/ListDataPenduduk'
import TambahDataPenduduk from './DataPenduduk/TambahDataPenduduk'
import EditDataPenduduk from './DataPenduduk/EditDataPenduduk'
import ListDataAkunPenduduk from './DataAkunPenduduk/ListDataAkunPenduduk'
import TambahAkunPenduduk from './DataAkunPenduduk/TambahAkunPenduduk'
import ListJenisDokumen from './JenisDokumen/ListJenisDokumen'
import TambahJenisDokumen from './JenisDokumen/TambahJenisDokumen'
import EditJenisDokumen from './JenisDokumen/EditJenisDokumen'
import ListArsipDokumen from './ArsipDokumen/ListArsipDokumen'
import TambahArsipDokumen from './ArsipDokumen/TambahArsipDokumen'
import ListDataAkunRW from './DataAkunRW/ListDataAkunRW'
import TambahAkunRW from './DataAkunRW/TambahAkunRW'
import ListPengajuan from './Pengajuan/ListPengajuan'

export {Beranda, ListDataPenduduk, TambahDataPenduduk, EditDataPenduduk, ListDataAkunPenduduk, TambahAkunPenduduk, ListJenisDokumen, TambahJenisDokumen, EditJenisDokumen, ListArsipDokumen, TambahArsipDokumen, ListDataAkunRW, TambahAkunRW, ListPengajuan}